#pragma once

#include <Common/Math/CoreNumericTypes.h>
#include <Common/EnumFlagOperators.h>
#include <Common/Memory/Containers/ForwardDeclarations/StringView.h>

namespace ngine::Input
{
	enum class KeyboardInput : uint16
	{
		Backspace = 0x08,
		Tab = 0x09,
		Enter = 0x0D,
		CapsLock = 20,
		LeftShift = 0xA0,
		RightShift = 0xA1,
		LeftControl = 0xA2,
		RightControl = 0XA3,
		LeftAlt = 0XA4,
		RightAlt = 0XA5,
		Escape = 0x1b,
		Space = 0x20,
		PageUp = 0x21,
		PageDown = 0x22,
		End = 0x23,
		Home = 0x24,
		ArrowLeft = 0x25,
		ArrowUp = 0x26,
		ArrowRight = 0x27,
		ArrowDown = 0x28,
		Insert = 0x2D,
		Delete = 0x2E,
		Zero = '0',
		One = '1',
		Two = '2',
		Three = '3',
		Four = '4',
		Five = '5',
		Six = '6',
		Seven = '7',
		Eight = '8',
		Nine = '9',
		A = 'A',
		B = 'B',
		C = 'C',
		D = 'D',
		E = 'E',
		F = 'F',
		G = 'G',
		H = 'H',
		I = 'I',
		J = 'J',
		K = 'K',
		L = 'L',
		M = 'M',
		N = 'N',
		O = 'O',
		P = 'P',
		Q = 'Q',
		R = 'R',
		S = 'S',
		T = 'T',
		U = 'U',
		V = 'V',
		W = 'W',
		X = 'X',
		Y = 'Y',
		Z = 'Z',
		ForwardSlash = '/',
		BackSlash = '\\',
		Quote = '\'',
		BackQuote = '`',
		DoubleQuote = '"',
		Period = 0xBE,
		Comma = 0xBC,
		Tilde = '~',
		Hyphen = '-',
		Minus = 0xBD,
		Plus = '+',
		Pipe = '|',
		Asterisk = '*',
		Underscore = '_',
		Ampersand = '&',
		Percent = '%',
		Dollar = '$',
		Hash = '#',
		Exclamation = '!',
		QuestionMark = '?',
		GreaterThan = '>',
		LessThan = '<',
		Equals = '=',
		Semicolon = ';',
		Colon = ':',
		At = '@',
		Circumflex = '^',
		Numpad0 = 0x60,
		Numpad1 = 0x61,
		Numpad2 = 0x62,
		Numpad3 = 0x63,
		Numpad4 = 0x64,
		Numpad5 = 0x65,
		Numpad6 = 0x66,
		Numpad7 = 0x67,
		Numpad8 = 0x68,
		Numpad9 = 0x69,
		Multiply = 0x6A,
		Add = 0x6B,
		Subtract = 0x6D,
		Decimal = 0x6E,
		Divide = 0x6F,
		RightCommand = 0xE3,
		LeftCommand = 0xE7,
		F1 = 0x70,
		F2 = 0x71,
		F3 = 0x72,
		F4 = 0x73,
		F5 = 0x74,
		F6 = 0x75,
		F7 = 0x76,
		F8 = 0x77,
		F9 = 0x78,
		F10 = 0x79,
		F11 = 0x80,
		F12 = 0x81,
		OpenBracket = 0xDD,
		CloseBracket = 0xBA,
		OpenCurlyBracket = '{',
		CloseCurlyBracket = '}',
		OpenParantheses = '(',
		CloseParantheses = ')',
		Unknown = 260,
		Count = 261
	};

	ENUM_FLAG_OPERATORS(KeyboardInput);

	[[nodiscard]] KeyboardInput GetKeyboardInputFromString(const ConstStringView string);
}
